- manifests/params.pp
- manifests/repo.pp
The package name is changed for Ubuntu and the apt module from Puppet needs the full fingerprint.
> Change apt key and change package name for Ubuntu.

- .fixtures.yaml
- .rspec
- Gemfile
- manifests/client.pp
- spec/classes/client_spec.rb
- spec/classes/init_spec.rb
- spec/classes/server_spec.rb
- spec/spec_helper.rb
- templates/10_ossec_agent.conf.erb
Ran into this when attempting an ossec server instance in AWS;  since EC2/R53/EIP interactions require the use of DNS, agent must be configured via server-hostname in lieu of server-ip.
apologies on the spec mess that was included.  went down a bit of a rabbit hole looking for a working spec/autorun configuration, but did not find anything conclusive beyond a few posts mentioning that it was no longer used?    added enough coverage to sanely do the hostname update, but should not be considered conclusive.
> Adding support for server-hostname in agent config

- templates/10_ossec.conf.erb
- templates/10_ossec_agent.conf.erb
The @path uses the puppet level path variable (which, gives all the path statements: /bin:/sbin:etc). We actually want the path from the each.
> Use internal path variable for erb in ossec config instead of global

- manifests/client.pp
- manifests/params.pp
- manifests/server.pp
Provides an option to tell the puppet module to not manage the client.keys file at all.
I don't want to the module to manage/overwrite it at all.
Not sure if you want to pull this, but I believe it could be useful. For someone with an existing OSSEC installation, this can prevent them from having their client.keys overwritten or deleted by the module.
> Manage client keys option

- manifests/client.pp
This should have been part of my previous pull request, but got missed. If the client.keys file on the agent does not exist yet, that means we want to have it register itself with the server.
> Manage client keys

- manifests/client.pp
The package on Ubuntu has permissions on the log directory of `0750`, so changing
the mode to `0755` is causing the permissions to be more lax.
> Change log directory to only be readable by user and group

- manifests/client.pp
This is primarily so I can supply `$::fqdn` as the `agent_name`.
> allow the agent identity to be modified

- manifests/client.pp
Because there are no relationships to determine consistent ordering, moving the agent-auth
exec to only be triggered if client keys aren't being managed is desirable. Else we can
have a situation where the `Exec` is triggered prior to the keys being added to disk.
> prevent the agent-auth command being used

- manifests/params.pp
- manifests/server.pp
- templates/10_process_list.erb
- templates/20_process_list.erb
- templates/80_ossec.conf.erb
This also required adding automation for the `.process_list` file which keeps track of any additional processes that need to be started/shutdown with ossec-hids.
> Add the ability to configure a MySQL database with OSSEC server

- manifests/server.pp
- templates/10_ossec.conf.erb
Enabling the Wazuh ruleset makes changes to the ossec.conf on the OSSEC server. Unfortunately the next time puppet runs on the OSSEC server, it wants to undo those changes.
This is a patch to help workaround that by allowing you to specify extra configurations for the <rules> section in the ossec.conf.
To use it, after enabling the Wazuh ruleset (either manually or via the automated script), take a look at the changes made to the ossec.conf file. You will need to put these same changes into the "$ossec_extra_rules_config" array parameter when calling the ossec::server class.
Consequently, if you add or remove any of the Wazuh rules later on, you'll need to ensure to add/remove the appropriate bits in the "$ossec_extra_rules_config" array parameter as well.
> Extra rules config

- manifests/client.pp
This commit alters the client manifest to use the agent key instead of fqdn
for the exported resource name. Since FQDN is not always unique this was
causing a duplicate resource error.
> Fix bug in client exported resources

- manifests/server.pp
If you are using mariadb, the module would fail as puppetmaster-mysql would try to install mysql-client, by setting $mariadb = true you can override the package name so it relies on the mariadb-client instead:
ex:
use_mysql        => true,
mariadb          => true,
mysql_hostname   => 'somehost',
mysql_name       => 'somedatabase',
mysql_username   => 'someuser',
mysql_password   => 'somepass',
Fixes #22
> MariaDB support

- manifests/server.pp
- templates/10_ossec.conf.erb
puppet module does not support disabling auto_ignore in syscheck.
This change will permit admin to disable auto_ignore for files which change more than three times.
> adding auto_ignore

- CHANGELOG
- manifests/client.pp
- templates/ar_repeated_offenders.erb
You can now set a minimal activeresponse entry containing just repeated_offenders by defining $ar_repeated_offenders in the ossec::client class:
class { "ossec::client":
ar_repeated_offenders => '100,200,300,400,500',
}
> repeated_offenders needs to be set for each agent.

- manifests/client.pp
- templates/10_ossec.conf.erb
when prelinking is enabled in the os, identical binaries are producing different hashes.  rhel6 for example enables prelinking by default.  ossec provides the functionality to prefilter file hashing with /usr/bin/prelink -y which will cause identical binaries to produce identical hashes.  this change will enable a variable, disabled by default, which will add the prefilter directive to the ossec.conf.erb.
> add variable to enable prefilter command

- manifests/client.pp
- manifests/params.pp
- manifests/server.pp
On RHEL7 systems the default provider does not correctly handle legacy init scripts, causing puppet to always change the service from stopped->running. Setting this to the 'redhat' provider allows puppet to correctly check the status of the service.
> set service provider to redhat on redhat systems

- manifests/server.pp
- templates/10_ossec.conf.erb
- templates/10_process_list.erb
- templates/20_process_list.erb
This pull request adds the option to enable syslog output, including specifying the syslog server and the format of the output. This can be useful for forwarding alerts into an ELK-like stack.
> Option to enable syslog output

- manifests/client.pp
Allow the client package and service names to be overridden via parameters to the ossec::client class.
> override package & service name for client installation

- manifests/client.pp
Modern packages on Debian include an init script which has a proper
status command. This allows users to override our default.
> client: allow configurable service_has_status, default to params

- manifests/repo.pp
Running this module with puppetlabs-apt v2.3.0 I was getting
warnings such as:
Warning: Scope(Apt::Source[wazuh]): $include_src is deprecated and
will be removed in the next major release, please use
$include => { 'src' => false } instead
> Fix apt deprecation warnings

- manifests/client.pp
- manifests/collect_agent_keys.pp
- manifests/export_agent_key.pp
- manifests/server.pp
For masterless puppet deployments exported resources generate
warnings.
Puppet will complain unless the exports/collection are moved to
separate modules that aren't included.
> Avoid warnings when storeconfigs are not available

- manifests/client.pp
- manifests/server.pp
The list of log files to monitor was configured in params.pp, but
was not used anywhere.
This meant that a default installation of this module would not
monitor any logs on either the client or server.
> Use default local_files setting

- manifests/params.pp
Changed param.pp "$::osfamily" switch statement string comparison to be an exact match for the puppet fact.
> Fixed osfamily letter casing for RedHat in params.pp

- manifests/server.pp
For users that prefer to manage a single `/var/ossec/etc/shared/agent.conf`, this allows us to provide our own template that will be rolled out to all clients rather than customizing `ossec.conf` on a per-client basis.  For those using this feature, the server's e.g. `ossec_scanpaths` is used.
I believe that this addresses #61
> Allow custom agent configurations

- metadata.json
jfryman-selinux is no more in dev.
it said that we should change this to puppet-selinux.
I applied this on the metadata.json file.
> use puppet-selinux instead of jfryman-selinux

- manifests/client.pp
- manifests/server.pp
For users that want to further finetune there ossec.conf, this allows to provide your own template without modifying the upstream module.
> allow custom ossec.conf template

- manifests/client.pp
- manifests/params.pp
Add the parameters for FreeBSD.
The ossec-hids application can be installed by the pkg manager on FreeBSD.
> Add FreeBSD support for client

- manifests/server.pp
- templates/10_ossec.conf.erb
Trying to add the ability to pass port number for the remote syslog output server. Based on the ossec documentation, the default value if not defined is always 514. 
This way if someone is using a non standard port, they can overwrite with the suitable value.
> Adding ability to pass syslog output port

- manifests/client.pp
- manifests/params.pp
- manifests/server.pp
- templates/10_ossec.conf.erb
- templates/10_ossec_agent.conf.erb
**1:** Adds default options for the `<rootcheck>` configuration in the `ossec.conf` for both the server and client. When rootcheck is enabled, 3 new options will be defined (where applicable). Previously it was not possible to define these options at all.
**2:** Adds the ability to toggle the `alert_new_files` option in the `<syscheck>` configuration. This was previous hardcoded to 'yes' (also now the default).
**More information:**
```
$ossec_alert_new_files   = 'yes',
$rootkit_files           = $::ossec::params::rootkit_files,
$rootkit_trojans         = $::ossec::params::rootkit_trojans,
$rootcheck_frequency     = 36000,
```
Resulting segment from `ossec.conf`:
```
<syscheckcheck>
<alert_new_files>yes</alert_new_files>
</syscheckcheck>
<rootcheck>
<frequency>36000</frequency> …
```
> Ability to configure rootkit options and toggle alert_new_files
